parameters:
  shopware.api_url: '%env(SHOPWARE_BASE_URL)%'
  shopware.integration_label: '%env(SHOPWARE_INTEGRATION_LABEL)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  MigrationSwinde\MigrationOxidToShopware\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Entity,Tests,Resources}'

  MigrationSwinde\MigrationOxidToShopware\Command\MigrateOxidCommand:
    arguments:
      $factory: '@MigrationSwinde\MigrationOxidToShopware\Service\CategoryMigratorFactory'
      $logger: '@monolog.logger.migration'
    tags: ['console.command']

  MigrationSwinde\MigrationOxidToShopware\Service\CategoryMigratorFactory:
    arguments:
      $configService: '@Shopware\Core\System\SystemConfig\SystemConfigService'
      $logger: '@monolog.logger.migration'
      $shopwareConnection: '@Doctrine\DBAL\Connection'
    public: true


